[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/roblox1/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/roblox1/*"
  to = "/roblox1/index.html"
  status = 200

[[redirects]]
  from = "/roblox1"
  to = "/roblox1/index.html"
  status = 200

